# Generated by Django 4.2.5 on 2024-01-06 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_verification_user_dislikes_user_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
