# Generated by Django 4.2.5 on 2024-01-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_verification_created_at_verification_is_alive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='is_alive',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
