# Generated by Django 4.2.5 on 2024-01-06 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
