# Generated by Django 4.2.5 on 2024-01-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cat", "0004_alter_catvote_cat"),
    ]

    operations = [
        migrations.AddField(
            model_name="cat",
            name="height",
            field=models.IntegerField(default=480),
        ),
        migrations.AddField(
            model_name="cat",
            name="width",
            field=models.IntegerField(default=480),
        ),
    ]
